<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>BaiTap3._4</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BaiTap3.1\BaiTap3.1.csproj" />
    <ProjectReference Include="..\BaiTap3.2\BaiTap3.2.csproj" />
    <ProjectReference Include="..\BaiTap3.3\BaiTap3.3.csproj" />
  </ItemGroup>

</Project>
